version: 2.1

orbs:
  architect: giantswarm/architect@6.3.2

workflows:
  build:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          registries-data: public gsoci.azurecr.io ACR_GSOCI_USERNAME ACR_GSOCI_PASSWORD true
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/
            branches:
              ignore:
                - main
                - master
