version: 2.1

orbs:
  architect: giantswarm/architect@6.3.2

workflows:
  test:
    jobs:
      - architect/go-build:
          context: architect
          name: go-build
          binary: template
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/
      # - architect/push-to-registries:
      #     context: architect
      #     name: push-to-registries
      #     requires:
      #       - go-build
      #     filters:
      #       # Trigger job also on git tag.
      #       tags:
      #         only: /^v.*/
      #       branches:
      #         ignore:
      #           - main
      #           - master
