version: 2.1

orbs:
  architect: giantswarm/architect@6.5.0

jobs:
  test:
    executor: architect/architect
    environment:
      DOCKER_BUILDKIT: '1' # needed to have docker
    steps:
      - setup_remote_docker
      - checkout # git repo is needed for architect to determine the version
      - run:
          name: Execute yamllint
          command: |
            container_tag=$(architect project version)
            docker run --rm -ti gsoci.azurecr.io/giantswarm/yamllint:$container_tag --version

workflows:
  build:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          registries-data: public gsoci.azurecr.io ACR_GSOCI_USERNAME ACR_GSOCI_PASSWORD true
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/
            branches:
              ignore:
                - main
      - test:
          context: architect
          requires:
            - push-to-registries
